//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayamGostarConsoleWcfSamples.PgForm {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgForm.GeneralCrmObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgForm.FormInfo))]
    public partial class BaseCrmObjectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CrmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrmObjectTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrmObjectTypeIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrmObjectTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgForm.BaseCrmObjectExtendedPropertyInfo[] ExtendedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentCrmObjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessStageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatDate {
            get {
                return this.CreatDateField;
            }
            set {
                if ((this.CreatDateField.Equals(value) != true)) {
                    this.CreatDateField = value;
                    this.RaisePropertyChanged("CreatDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmId {
            get {
                return this.CrmIdField;
            }
            set {
                if ((this.CrmIdField.Equals(value) != true)) {
                    this.CrmIdField = value;
                    this.RaisePropertyChanged("CrmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeCode {
            get {
                return this.CrmObjectTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CrmObjectTypeCodeField, value) != true)) {
                    this.CrmObjectTypeCodeField = value;
                    this.RaisePropertyChanged("CrmObjectTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrmObjectTypeIndex {
            get {
                return this.CrmObjectTypeIndexField;
            }
            set {
                if ((this.CrmObjectTypeIndexField.Equals(value) != true)) {
                    this.CrmObjectTypeIndexField = value;
                    this.RaisePropertyChanged("CrmObjectTypeIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeName {
            get {
                return this.CrmObjectTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CrmObjectTypeNameField, value) != true)) {
                    this.CrmObjectTypeNameField = value;
                    this.RaisePropertyChanged("CrmObjectTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgForm.BaseCrmObjectExtendedPropertyInfo[] ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate {
            get {
                return this.ModifyDateField;
            }
            set {
                if ((this.ModifyDateField.Equals(value) != true)) {
                    this.ModifyDateField = value;
                    this.RaisePropertyChanged("ModifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentCrmObjectId {
            get {
                return this.ParentCrmObjectIdField;
            }
            set {
                if ((this.ParentCrmObjectIdField.Equals(value) != true)) {
                    this.ParentCrmObjectIdField = value;
                    this.RaisePropertyChanged("ParentCrmObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessStage {
            get {
                return this.ProcessStageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessStageField, value) != true)) {
                    this.ProcessStageField = value;
                    this.RaisePropertyChanged("ProcessStage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId {
            get {
                return this.RefIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RefIdField, value) != true)) {
                    this.RefIdField = value;
                    this.RaisePropertyChanged("RefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgForm.FormInfo))]
    public partial class GeneralCrmObjectInfo : PayamGostarConsoleWcfSamples.PgForm.BaseCrmObjectInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdentityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdentityId {
            get {
                return this.IdentityIdField;
            }
            set {
                if ((this.IdentityIdField.Equals(value) != true)) {
                    this.IdentityIdField = value;
                    this.RaisePropertyChanged("IdentityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FormInfo : PayamGostarConsoleWcfSamples.PgForm.GeneralCrmObjectInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectExtendedPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class BaseCrmObjectExtendedPropertyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey {
            get {
                return this.UserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                    this.UserKeyField = value;
                    this.RaisePropertyChanged("UserKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgForm.FormInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult))]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FormInfoResult : PayamGostarConsoleWcfSamples.PgForm.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgForm.FormInfo FormInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgForm.FormInfo[] FormInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgForm.FormInfo FormInfo {
            get {
                return this.FormInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.FormInfoField, value) != true)) {
                    this.FormInfoField = value;
                    this.RaisePropertyChanged("FormInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgForm.FormInfo[] FormInfoList {
            get {
                return this.FormInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.FormInfoListField, value) != true)) {
                    this.FormInfoListField = value;
                    this.RaisePropertyChanged("FormInfoList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCrmObjectResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SaveCrmObjectResult : PayamGostarConsoleWcfSamples.PgForm.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CrmIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmId {
            get {
                return this.CrmIdField;
            }
            set {
                if ((this.CrmIdField.Equals(value) != true)) {
                    this.CrmIdField = value;
                    this.RaisePropertyChanged("CrmId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectDeleteOption", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.BusinessLogicLayer.Enti" +
        "ties.PayamGostar")]
    public enum CrmObjectDeleteOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignChildrenToParent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteChildren = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletePersons = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteWithHistory = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgForm.IForm")]
    public interface IForm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/SaveForm", ReplyAction="http://tempuri.org/IForm/SaveFormResponse")]
        PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult SaveForm(string userName, string password, PayamGostarConsoleWcfSamples.PgForm.FormInfo formInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/SaveForm", ReplyAction="http://tempuri.org/IForm/SaveFormResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult> SaveFormAsync(string userName, string password, PayamGostarConsoleWcfSamples.PgForm.FormInfo formInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/SearchForm", ReplyAction="http://tempuri.org/IForm/SearchFormResponse")]
        PayamGostarConsoleWcfSamples.PgForm.FormInfoResult SearchForm(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/SearchForm", ReplyAction="http://tempuri.org/IForm/SearchFormResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.FormInfoResult> SearchFormAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/FindFormById", ReplyAction="http://tempuri.org/IForm/FindFormByIdResponse")]
        PayamGostarConsoleWcfSamples.PgForm.FormInfoResult FindFormById(string username, string password, System.Guid formId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/FindFormById", ReplyAction="http://tempuri.org/IForm/FindFormByIdResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.FormInfoResult> FindFormByIdAsync(string username, string password, System.Guid formId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/DeleteFormById", ReplyAction="http://tempuri.org/IForm/DeleteFormByIdResponse")]
        PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult DeleteFormById(string userName, string password, System.Guid formId, PayamGostarConsoleWcfSamples.PgForm.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForm/DeleteFormById", ReplyAction="http://tempuri.org/IForm/DeleteFormByIdResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult> DeleteFormByIdAsync(string userName, string password, System.Guid formId, PayamGostarConsoleWcfSamples.PgForm.CrmObjectDeleteOption deleteOption);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFormChannel : PayamGostarConsoleWcfSamples.PgForm.IForm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormClient : System.ServiceModel.ClientBase<PayamGostarConsoleWcfSamples.PgForm.IForm>, PayamGostarConsoleWcfSamples.PgForm.IForm {
        
        public FormClient() {
        }
        
        public FormClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult SaveForm(string userName, string password, PayamGostarConsoleWcfSamples.PgForm.FormInfo formInfo) {
            return base.Channel.SaveForm(userName, password, formInfo);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult> SaveFormAsync(string userName, string password, PayamGostarConsoleWcfSamples.PgForm.FormInfo formInfo) {
            return base.Channel.SaveFormAsync(userName, password, formInfo);
        }
        
        public PayamGostarConsoleWcfSamples.PgForm.FormInfoResult SearchForm(string userName, string password, string typeKey, string query) {
            return base.Channel.SearchForm(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.FormInfoResult> SearchFormAsync(string userName, string password, string typeKey, string query) {
            return base.Channel.SearchFormAsync(userName, password, typeKey, query);
        }
        
        public PayamGostarConsoleWcfSamples.PgForm.FormInfoResult FindFormById(string username, string password, System.Guid formId) {
            return base.Channel.FindFormById(username, password, formId);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.FormInfoResult> FindFormByIdAsync(string username, string password, System.Guid formId) {
            return base.Channel.FindFormByIdAsync(username, password, formId);
        }
        
        public PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult DeleteFormById(string userName, string password, System.Guid formId, PayamGostarConsoleWcfSamples.PgForm.CrmObjectDeleteOption deleteOption) {
            return base.Channel.DeleteFormById(userName, password, formId, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgForm.SaveCrmObjectResult> DeleteFormByIdAsync(string userName, string password, System.Guid formId, PayamGostarConsoleWcfSamples.PgForm.CrmObjectDeleteOption deleteOption) {
            return base.Channel.DeleteFormByIdAsync(userName, password, formId, deleteOption);
        }
    }
}
