//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayamGostarConsoleWcfSamples.PgPerson {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.IdentityInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.OrganizationInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.PersonInfo))]
    public partial class BaseCrmObjectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CrmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrmObjectTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrmObjectTypeIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrmObjectTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.BaseCrmObjectExtendedPropertyInfo[] ExtendedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentCrmObjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessStageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatDate {
            get {
                return this.CreatDateField;
            }
            set {
                if ((this.CreatDateField.Equals(value) != true)) {
                    this.CreatDateField = value;
                    this.RaisePropertyChanged("CreatDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmId {
            get {
                return this.CrmIdField;
            }
            set {
                if ((this.CrmIdField.Equals(value) != true)) {
                    this.CrmIdField = value;
                    this.RaisePropertyChanged("CrmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeCode {
            get {
                return this.CrmObjectTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CrmObjectTypeCodeField, value) != true)) {
                    this.CrmObjectTypeCodeField = value;
                    this.RaisePropertyChanged("CrmObjectTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrmObjectTypeIndex {
            get {
                return this.CrmObjectTypeIndexField;
            }
            set {
                if ((this.CrmObjectTypeIndexField.Equals(value) != true)) {
                    this.CrmObjectTypeIndexField = value;
                    this.RaisePropertyChanged("CrmObjectTypeIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeName {
            get {
                return this.CrmObjectTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CrmObjectTypeNameField, value) != true)) {
                    this.CrmObjectTypeNameField = value;
                    this.RaisePropertyChanged("CrmObjectTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.BaseCrmObjectExtendedPropertyInfo[] ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate {
            get {
                return this.ModifyDateField;
            }
            set {
                if ((this.ModifyDateField.Equals(value) != true)) {
                    this.ModifyDateField = value;
                    this.RaisePropertyChanged("ModifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentCrmObjectId {
            get {
                return this.ParentCrmObjectIdField;
            }
            set {
                if ((this.ParentCrmObjectIdField.Equals(value) != true)) {
                    this.ParentCrmObjectIdField = value;
                    this.RaisePropertyChanged("ParentCrmObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessStage {
            get {
                return this.ProcessStageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessStageField, value) != true)) {
                    this.ProcessStageField = value;
                    this.RaisePropertyChanged("ProcessStage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId {
            get {
                return this.RefIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RefIdField, value) != true)) {
                    this.RefIdField = value;
                    this.RaisePropertyChanged("RefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.OrganizationInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.PersonInfo))]
    public partial class IdentityInfo : PayamGostarConsoleWcfSamples.PgPerson.BaseCrmObjectInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.IdentityContactAddress[] AddressContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.CategoryInfo[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CustomerDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DontEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DontFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DontPhoneCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DontSmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DontSocialSmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EmailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.IdentityContactPhone[] PhoneContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaleUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.IdentityContactAddress[] AddressContacts {
            get {
                return this.AddressContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressContactsField, value) != true)) {
                    this.AddressContactsField = value;
                    this.RaisePropertyChanged("AddressContacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.CategoryInfo[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificationField, value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName {
            get {
                return this.ColorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorNameField, value) != true)) {
                    this.ColorNameField = value;
                    this.RaisePropertyChanged("ColorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CustomerDate {
            get {
                return this.CustomerDateField;
            }
            set {
                if ((this.CustomerDateField.Equals(value) != true)) {
                    this.CustomerDateField = value;
                    this.RaisePropertyChanged("CustomerDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber {
            get {
                return this.CustomerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNumberField, value) != true)) {
                    this.CustomerNumberField = value;
                    this.RaisePropertyChanged("CustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontEmail {
            get {
                return this.DontEmailField;
            }
            set {
                if ((this.DontEmailField.Equals(value) != true)) {
                    this.DontEmailField = value;
                    this.RaisePropertyChanged("DontEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontFax {
            get {
                return this.DontFaxField;
            }
            set {
                if ((this.DontFaxField.Equals(value) != true)) {
                    this.DontFaxField = value;
                    this.RaisePropertyChanged("DontFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontPhoneCall {
            get {
                return this.DontPhoneCallField;
            }
            set {
                if ((this.DontPhoneCallField.Equals(value) != true)) {
                    this.DontPhoneCallField = value;
                    this.RaisePropertyChanged("DontPhoneCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontSms {
            get {
                return this.DontSmsField;
            }
            set {
                if ((this.DontSmsField.Equals(value) != true)) {
                    this.DontSmsField = value;
                    this.RaisePropertyChanged("DontSms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontSocialSms {
            get {
                return this.DontSocialSmsField;
            }
            set {
                if ((this.DontSocialSmsField.Equals(value) != true)) {
                    this.DontSocialSmsField = value;
                    this.RaisePropertyChanged("DontSocialSms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Emails {
            get {
                return this.EmailsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailsField, value) != true)) {
                    this.EmailsField = value;
                    this.RaisePropertyChanged("Emails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityType {
            get {
                return this.IdentityTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityTypeField, value) != true)) {
                    this.IdentityTypeField = value;
                    this.RaisePropertyChanged("IdentityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherUsername {
            get {
                return this.OtherUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherUsernameField, value) != true)) {
                    this.OtherUsernameField = value;
                    this.RaisePropertyChanged("OtherUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.IdentityContactPhone[] PhoneContacts {
            get {
                return this.PhoneContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneContactsField, value) != true)) {
                    this.PhoneContactsField = value;
                    this.RaisePropertyChanged("PhoneContacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaleUsername {
            get {
                return this.SaleUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleUsernameField, value) != true)) {
                    this.SaleUsernameField = value;
                    this.RaisePropertyChanged("SaleUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceType {
            get {
                return this.SourceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceTypeField, value) != true)) {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportUsername {
            get {
                return this.SupportUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportUsernameField, value) != true)) {
                    this.SupportUsernameField = value;
                    this.RaisePropertyChanged("SupportUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class OrganizationInfo : PayamGostarConsoleWcfSamples.PgPerson.IdentityInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EconomicCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnershipTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.EmployeeInfo[] PersonnelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegisterDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrademarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessType {
            get {
                return this.BusinessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessTypeField, value) != true)) {
                    this.BusinessTypeField = value;
                    this.RaisePropertyChanged("BusinessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EconomicCode {
            get {
                return this.EconomicCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EconomicCodeField, value) != true)) {
                    this.EconomicCodeField = value;
                    this.RaisePropertyChanged("EconomicCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnershipType {
            get {
                return this.OwnershipTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnershipTypeField, value) != true)) {
                    this.OwnershipTypeField = value;
                    this.RaisePropertyChanged("OwnershipType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.EmployeeInfo[] Personnel {
            get {
                return this.PersonnelField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonnelField, value) != true)) {
                    this.PersonnelField = value;
                    this.RaisePropertyChanged("Personnel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegisterDate {
            get {
                return this.RegisterDateField;
            }
            set {
                if ((this.RegisterDateField.Equals(value) != true)) {
                    this.RegisterDateField = value;
                    this.RaisePropertyChanged("RegisterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterNumber {
            get {
                return this.RegisterNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterNumberField, value) != true)) {
                    this.RegisterNumberField = value;
                    this.RaisePropertyChanged("RegisterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareType {
            get {
                return this.ShareTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareTypeField, value) != true)) {
                    this.ShareTypeField = value;
                    this.RaisePropertyChanged("ShareType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeType {
            get {
                return this.TradeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeTypeField, value) != true)) {
                    this.TradeTypeField = value;
                    this.RaisePropertyChanged("TradeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trademark {
            get {
                return this.TrademarkField;
            }
            set {
                if ((object.ReferenceEquals(this.TrademarkField, value) != true)) {
                    this.TrademarkField = value;
                    this.RaisePropertyChanged("Trademark");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PersonInfo : PayamGostarConsoleWcfSamples.PgPerson.IdentityInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreasOfInterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.EmployeeInfo[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HobbiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MannerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentStatusTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonPrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefferedContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreasOfInterest {
            get {
                return this.AreasOfInterestField;
            }
            set {
                if ((object.ReferenceEquals(this.AreasOfInterestField, value) != true)) {
                    this.AreasOfInterestField = value;
                    this.RaisePropertyChanged("AreasOfInterest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditType {
            get {
                return this.CreditTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditTypeField, value) != true)) {
                    this.CreditTypeField = value;
                    this.RaisePropertyChanged("CreditType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Degree {
            get {
                return this.DegreeField;
            }
            set {
                if ((object.ReferenceEquals(this.DegreeField, value) != true)) {
                    this.DegreeField = value;
                    this.RaisePropertyChanged("Degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.EmployeeInfo[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUsername {
            get {
                return this.FacebookUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUsernameField, value) != true)) {
                    this.FacebookUsernameField = value;
                    this.RaisePropertyChanged("FacebookUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hobbies {
            get {
                return this.HobbiesField;
            }
            set {
                if ((object.ReferenceEquals(this.HobbiesField, value) != true)) {
                    this.HobbiesField = value;
                    this.RaisePropertyChanged("Hobbies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MannerType {
            get {
                return this.MannerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MannerTypeField, value) != true)) {
                    this.MannerTypeField = value;
                    this.RaisePropertyChanged("MannerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode {
            get {
                return this.NationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalCodeField, value) != true)) {
                    this.NationalCodeField = value;
                    this.RaisePropertyChanged("NationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatusType {
            get {
                return this.PaymentStatusTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentStatusTypeField, value) != true)) {
                    this.PaymentStatusTypeField = value;
                    this.RaisePropertyChanged("PaymentStatusType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonPrefix {
            get {
                return this.PersonPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonPrefixField, value) != true)) {
                    this.PersonPrefixField = value;
                    this.RaisePropertyChanged("PersonPrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrefferedContactType {
            get {
                return this.PrefferedContactTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefferedContactTypeField, value) != true)) {
                    this.PrefferedContactTypeField = value;
                    this.RaisePropertyChanged("PrefferedContactType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spouse {
            get {
                return this.SpouseField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseField, value) != true)) {
                    this.SpouseField = value;
                    this.RaisePropertyChanged("Spouse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectExtendedPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class BaseCrmObjectExtendedPropertyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey {
            get {
                return this.UserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                    this.UserKeyField = value;
                    this.RaisePropertyChanged("UserKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityContactAddress", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class IdentityContactAddress : PayamGostarConsoleWcfSamples.PgPerson.IdentityContact {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypeField, value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipBox {
            get {
                return this.ZipBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipBoxField, value) != true)) {
                    this.ZipBoxField = value;
                    this.RaisePropertyChanged("ZipBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CategoryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdentityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdentityId {
            get {
                return this.IdentityIdField;
            }
            set {
                if ((this.IdentityIdField.Equals(value) != true)) {
                    this.IdentityIdField = value;
                    this.RaisePropertyChanged("IdentityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityContactPhone", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class IdentityContactPhone : PayamGostarConsoleWcfSamples.PgPerson.IdentityContact {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinuedNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonePrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContinuedNumber {
            get {
                return this.ContinuedNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinuedNumberField, value) != true)) {
                    this.ContinuedNumberField = value;
                    this.RaisePropertyChanged("ContinuedNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhonePrefix {
            get {
                return this.PhonePrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonePrefixField, value) != true)) {
                    this.PhonePrefixField = value;
                    this.RaisePropertyChanged("PhonePrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneType {
            get {
                return this.PhoneTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneTypeField, value) != true)) {
                    this.PhoneTypeField = value;
                    this.RaisePropertyChanged("PhoneType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Office {
            get {
                return this.OfficeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeField, value) != true)) {
                    this.OfficeField = value;
                    this.RaisePropertyChanged("Office");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((this.OrganizationIdField.Equals(value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profession {
            get {
                return this.ProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionField, value) != true)) {
                    this.ProfessionField = value;
                    this.RaisePropertyChanged("Profession");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityContact", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.IdentityContactPhone))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.IdentityContactAddress))]
    public partial class IdentityContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult))]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PersonInfoResult : PayamGostarConsoleWcfSamples.PgPerson.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.PersonInfo PersonInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PayamGostarConsoleWcfSamples.PgPerson.PersonInfo[] PersonInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.PersonInfo PersonInfo {
            get {
                return this.PersonInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonInfoField, value) != true)) {
                    this.PersonInfoField = value;
                    this.RaisePropertyChanged("PersonInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamGostarConsoleWcfSamples.PgPerson.PersonInfo[] PersonInfoList {
            get {
                return this.PersonInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonInfoListField, value) != true)) {
                    this.PersonInfoListField = value;
                    this.RaisePropertyChanged("PersonInfoList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCrmObjectResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SaveCrmObjectResult : PayamGostarConsoleWcfSamples.PgPerson.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CrmIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmId {
            get {
                return this.CrmIdField;
            }
            set {
                if ((this.CrmIdField.Equals(value) != true)) {
                    this.CrmIdField = value;
                    this.RaisePropertyChanged("CrmId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectDeleteOption", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.BusinessLogicLayer.Enti" +
        "ties.PayamGostar")]
    public enum CrmObjectDeleteOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignChildrenToParent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteChildren = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletePersons = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteWithHistory = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgPerson.IPerson")]
    public interface IPerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/SavePerson", ReplyAction="http://tempuri.org/IPerson/SavePersonResponse")]
        PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult SavePerson(string username, string password, PayamGostarConsoleWcfSamples.PgPerson.PersonInfo person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/SavePerson", ReplyAction="http://tempuri.org/IPerson/SavePersonResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult> SavePersonAsync(string username, string password, PayamGostarConsoleWcfSamples.PgPerson.PersonInfo person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/SearchPerson", ReplyAction="http://tempuri.org/IPerson/SearchPersonResponse")]
        PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult SearchPerson(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/SearchPerson", ReplyAction="http://tempuri.org/IPerson/SearchPersonResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult> SearchPersonAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/DeletePersonById", ReplyAction="http://tempuri.org/IPerson/DeletePersonByIdResponse")]
        PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult DeletePersonById(string username, string password, System.Guid personId, PayamGostarConsoleWcfSamples.PgPerson.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/DeletePersonById", ReplyAction="http://tempuri.org/IPerson/DeletePersonByIdResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult> DeletePersonByIdAsync(string username, string password, System.Guid personId, PayamGostarConsoleWcfSamples.PgPerson.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/FindPersonById", ReplyAction="http://tempuri.org/IPerson/FindPersonByIdResponse")]
        PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult FindPersonById(string username, string password, System.Guid personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/FindPersonById", ReplyAction="http://tempuri.org/IPerson/FindPersonByIdResponse")]
        System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult> FindPersonByIdAsync(string username, string password, System.Guid personId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonChannel : PayamGostarConsoleWcfSamples.PgPerson.IPerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonClient : System.ServiceModel.ClientBase<PayamGostarConsoleWcfSamples.PgPerson.IPerson>, PayamGostarConsoleWcfSamples.PgPerson.IPerson {
        
        public PersonClient() {
        }
        
        public PersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult SavePerson(string username, string password, PayamGostarConsoleWcfSamples.PgPerson.PersonInfo person) {
            return base.Channel.SavePerson(username, password, person);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult> SavePersonAsync(string username, string password, PayamGostarConsoleWcfSamples.PgPerson.PersonInfo person) {
            return base.Channel.SavePersonAsync(username, password, person);
        }
        
        public PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult SearchPerson(string userName, string password, string typeKey, string query) {
            return base.Channel.SearchPerson(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult> SearchPersonAsync(string userName, string password, string typeKey, string query) {
            return base.Channel.SearchPersonAsync(userName, password, typeKey, query);
        }
        
        public PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult DeletePersonById(string username, string password, System.Guid personId, PayamGostarConsoleWcfSamples.PgPerson.CrmObjectDeleteOption deleteOption) {
            return base.Channel.DeletePersonById(username, password, personId, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.SaveCrmObjectResult> DeletePersonByIdAsync(string username, string password, System.Guid personId, PayamGostarConsoleWcfSamples.PgPerson.CrmObjectDeleteOption deleteOption) {
            return base.Channel.DeletePersonByIdAsync(username, password, personId, deleteOption);
        }
        
        public PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult FindPersonById(string username, string password, System.Guid personId) {
            return base.Channel.FindPersonById(username, password, personId);
        }
        
        public System.Threading.Tasks.Task<PayamGostarConsoleWcfSamples.PgPerson.PersonInfoResult> FindPersonByIdAsync(string username, string password, System.Guid personId) {
            return base.Channel.FindPersonByIdAsync(username, password, personId);
        }
    }
}
